apiVersion: v1
kind: Pod
metadata:
  name: exec
  labels:
    name: exec
spec:
  containers:
  - name: exec
    image: busybox
    command: # => entrypoint
      - /bin/sh
    args: # => cmd
      - -c
      - touch /tmp/feliznavida.txt; sleep 120;
  restartPolicy: Never
