services:
  web:
    image: lufertony/simulador-do-caos:v2
    ports:
      - 8080:3000
    restart: always
    # healthcheck:
      # test: ["CMD", "curl","-f","http://localhost:3000/healthcheck"]
      # interval: 5s
      # timeout: 10s
      # retries: 2
      # start_period: 30s
      # disable: true
    cpuset: "4"
    memswap_limit: 512M
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M