apiVersion: apps/v1
kind: Deployment
metadata:
  name: caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caos
  template:
    metadata:
      labels:
        app: caos
    spec:
      containers:
        - name: caos
          image: lufertony/simulador-do-caos:v1
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: /health
              httpHeaders:
                - name: token
                  value: kajsdkhsjkdh
            initialDelaySeconds: 5 # -> tempo para comecar a testar o endpoint apos o start do container
            periodSeconds: 10 # -> intervalo entre as chamadas
            failureThreshold: 1 # -> quantidade de tolerancia de erro
            successThreshold: 1 # -> quantidade de sucesso para zerar o contador de erro
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 3000
              path: /ready
              httpHeaders:
                - name: token
                  value: kajsdkhsjkdh5
            initialDelaySeconds: 3
            periodSeconds: 4
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              port: 3000
              path: /health
            failureThreshold: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: caos
spec:
  selector:
    app: caos
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
