# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: caos
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: caos
#   template:
#     metadata:
#       labels:
#         app: caos
#     spec:
#       containers:
#       - name: caos
#         image: lufertony/simulador-do-caos:v1
#         ports:
#         - containerPort: 3000
#       restartPolicy: onFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: caos
  labels:
    app: caos
spec:
  containers:
  - name: caos
    image: lufertony/simulador-do-caos:v1
    ports:
    - containerPort: 3000
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: caos
spec:
  selector:
    app: caos
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
    protocol: TCP
    nodePort: 30000

